name: dirk hagen
favicon: null
layout_spectrum: 0.23545664781704545
typography_spectrum: 0.2749169245362282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5540441093035042
  lightness: 0.26126575469970703
  saturation: 0.6880078641697764
  rhythmicContrast: 0.7757062048185617
purpose: []
